steps:
  - label: ":go: :test_tube: Run tests"
    command: "./gotest.sh"
    plugins:
      - /Users/jeremy/dev/plugins/vault-secrets-buildkite-plugin#update-vault-login:
          server: "http://localhost:8200"
          path: secret/buildkite
          auth:
            method: approle
            role-id: "293c201b-3693-7f52-a8da-44ea8a0ca2cd"