steps:
  - label: ":go: :test_tube: Run tests"
    command: "./gotest.sh"
    plugins:
      - buildkite-plugins/vault-secrets#update-vault-login:
          server: localhost
          path: buildkite/agent
          auth-method: approle
          role-id: buildkite-agent
          secret-id: "$$VAULT_SECRET_ID"
          secrets:
            - test-analytics
