steps:
  - label: ":go: :test_tube: Run tests"
    command: "./gotest.sh"
    plugins:
      - vault-secrets-buildkite-plugin#v0.2.0:
          server: "http://localhost:8200"
          path: secret/buildkite
          auth:
            method: approle
            role-id: "293c201b-3693-7f52-a8da-44ea8a0ca2cd"
            secret-env: "SOME_VAULT_SECRET_ID"